/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/17fc403a-14fe-4bbe-9a0d-7373aa908f89 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float lowerbound;
  float moistureValue;
  float upperbound;
  CloudPercentage moisturePerc;
  bool pumpState;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <LiquidCrystal_I2C.h>

#define waterValue 270   // Define max value we consider soil 'wet'
#define airValue 1024   // Define min value we consider soil 'dry'
#define relayPin D0


//Initialize the LCD display
LiquidCrystal_I2C lcd(0x27, 16, 2);


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(A0,INPUT);
  pinMode(relayPin,OUTPUT);
  
  lcd.init();
  lcd.backlight();
  lcd.setCursor(1, 0);
  lcd.print("System Loading");
  for (int a = 0; a <= 5; a++) {
    lcd.setCursor(a, 1);
    lcd.print(".");
    delay(500);
  }
  lcd.clear();
  
  digitalWrite(relayPin, HIGH);
  pumpState = 0;
  lowerbound = 35;
  upperbound = 60;
}

void loop() {
  ArduinoCloud.update();

  getMoisture();
  checkState();
  delay(100);
}

float getMoisture() {
  float moistureValue = analogRead(A0);
  moisturePerc = map(moistureValue, airValue, waterValue, 0, 100);
  // Serial.print("Moisture value: ");
  // Serial.println(moistureValue);
  // Serial.print("Moisture percentage: ");
  // Serial.println(moisturePerc);
  lcd.setCursor(0, 0);
  lcd.print("Moisture: ");
  lcd.print(moistureValue);
  lcd.setCursor(0, 1);
  lcd.print("Percent: ");
  lcd.print(moisturePerc);
}

void checkState() {
  
  if(moisturePerc < lowerbound) {
    Serial.println("Nearly dry, Pump on");
    digitalWrite(relayPin, LOW); // low signal to relay gives high signal to pump
    pumpState = 1;
    delay(1000);
  }
  else if(moisturePerc > upperbound) // max water level should be
  {
    Serial.println("Nearly wet, Pump off");
    digitalWrite(relayPin, HIGH); // high signal to relay gives low signal to pump
    pumpState = 0;
    delay(1000);
    // ESP.deepSleep(10e6);
  }
  
  Serial.print("relayPin ");
  if(digitalRead(relayPin) == LOW) Serial.println("Pump ON");
  else Serial.println("Pump OFF");
}


/*
  Since PumpState is READ_WRITE variable, onPumpStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPumpStateChange()  {
  
  if(pumpState == 1) {
    Serial.println("Pump turning ON using DASHBOARD");
    digitalWrite(relayPin, LOW); // low signal to relay gives high signal to pump
    delay(10000); 
  }
  else {
    Serial.println("Pump turning OFF using DASHBOARD");
    digitalWrite(relayPin, HIGH); // high signal to relay gives low signal to pump
    delay(10000);
    // ESP.deepSleep(20e6);
  }
  
  Serial.print("In onchange relayPin ");
  if(digitalRead(relayPin) == LOW) Serial.println("Pump ON");
  else Serial.println("Pump OFF");
}





/*
  Since Lowerbound is READ_WRITE variable, onLowerboundChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLowerboundChange()  {
  // Add your code here to act upon Lowerbound change
}

/*
  Since Upperbound is READ_WRITE variable, onUpperboundChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onUpperboundChange()  {
  // Add your code here to act upon Upperbound change
}
